
services:
  backend:
    build: ./backend
    container_name: elearning-backend
    restart: always
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    command: node index.js

  frontend:
    build: ./frontend
    container_name: elearning-frontend
    restart: always
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: elearning-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elearning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
